
database0:
    username: root
    password: lc121718
    url: jdbc:mysql://47.93.245.76:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    databaseName: test
    druid:
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 3000



dubbo:
  application:
    name: springboot-dubbo-server
  registry:
    protocol: zookeeper
    address: lcyanxi03:2181
  protocol:
    name: dubbo
    port: 20887
  version: 1.0.0
  scan:
    base-packages: com.lcyanxi.impl